/* tslint:disable */
// This file is generated
// Do not edit this file
import * as generateImage from "./generateImage/index";
export * as generateImage from "./generateImage/index";

export type Actions = {
  generateImage: generateImage.ActionGenerateImage;
}
